name: 'fpl_mentat'
version: '0.1.3'

profile: 'fpl_mentat'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


# Configuring models
models:
  fpl_mentat:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
