select
	ip.player_id,
	ip.gameweek,
	ip.next_gw_fixture_cnt,
	ip.fixture_cnt_gw3,
	ip.fixture_cnt_gw5,
	ip.position,
	ip.team_id,
	ip.opponent_id,
	ip.home_or_away,
	ip.fixture_difficulty,
	ip.avg_minutes_gw3,
	ip.avg_minutes_gw5,
	ip.avg_goals_scored_gw3, 
	ip.avg_goals_scored_gw5,
	ip.avg_assists_gw3, 
	ip.avg_assists_gw5,	
	ip.avg_xG_gw3, 
	ip.avg_xG_gw5, 
	ip.avg_xA_gw3,
	ip.avg_xA_gw5, 
	ip.avg_bonus_gw3, 
	ip.avg_bonus_gw5, 
	ip.avg_bps_gw3,
	ip.avg_bps_gw5, 
	ip.avg_clean_sheets_gw3, 
	ip.avg_clean_sheets_gw5,
	ip.avg_goals_conceded_gw3, 
	ip.avg_goals_conceded_gw5,
	ip.avg_yellow_cards_gw3,
	ip.avg_yellow_cards_gw5,
	ip.avg_red_cards_gw3,
	ip.avg_red_cards_gw5,
	ip.avg_saves_gw3,
	ip.avg_saves_gw5, 
	ip.avg_threat_gw3, 
	ip.avg_threat_gw5,
	ip.avg_creativity_gw3, 
	ip.avg_creativity_gw5, 
	ip.avg_expected_goal_involvements_gw3,
	ip.avg_expected_goal_involvements_gw5, 
	ip.avg_expected_goals_conceded_gw3,
	ip.avg_expected_goals_conceded_gw5,
	ip.avg_recoveries_gw3,
	ip.avg_recoveries_gw5,
	ip.avg_tackles_gw3,
	ip.avg_tackles_gw5,
	ip.avg_defensive_contribution_gw3,
	ip.avg_defensive_contribution_gw5,
	ip.avg_clearances_blocks_interceptions_gw3,
	ip.avg_clearances_blocks_interceptions_gw5,
	ip.penalties_missed_season,
	ip.penalties_saved_season,
	ip.starts_gw3,
	ip.starts_gw5,
	ip.penalty_order,
	ip.fk_order,
	ip.corners_order,
	ts.avg_goals_scored_gw3 as team_avg_goals_scored_gw3,
	ts.avg_goals_scored_gw5 as team_avg_goals_scored_gw5,
	ts.avg_goals_conceded_gw3 as team_avg_goals_conceded_gw3,
	ts.avg_goals_conceded_gw5 as team_avg_goals_conceded_gw5,
	os.avg_goals_scored_gw3 as opp_avg_goals_scored_gw3,
	os.avg_goals_scored_gw5 as opp_avg_goals_scored_gw5,
	os.avg_goals_conceded_gw3 as opp_avg_goals_conceded_gw3,
	os.avg_goals_conceded_gw5 as opp_avg_goals_conceded_gw5,
	ip.avg_total_points_gw3,
	ip.avg_total_points_gw5,
	ip.avg_total_points_gw5-ip.avg_total_points_gw3 as form_trend,
	ip.minutes_variability,
	ip.had_blank_gw,
	case 
		when d.deadline_time < current_timestamp then 'N'
		when d.deadline_time > current_timestamp then 'Y'
		else 'N'
	end as is_prediction_row,
	ip.total_points as target_total_points
from {{ ref('int_player_rolling') }} ip
left join {{ ref('int_team_stats_rolling') }} ts
	on ip.team_id = ts.team_id and ip.gameweek = ts.gameweek
left join {{ ref('int_team_stats_rolling') }} os
	on ip.opponent_id = os.team_id and ip.gameweek = os.gameweek
left join {{ ref('dim_deadlines') }} d
	on d.gameweek = ip.gameweek
