select
    id as player_id,
    gameweek,
    "stats.minutes" as minutes,
    "stats.goals_scored" as goals_scored,
    "stats.assists" as assists,
    "stats.clean_sheets" as clean_sheets,
    "stats.goals_conceded" as goals_conceded,
    "stats.penalties_missed" as penalties_missed,
    "stats.penalties_saved" as penalties_saved,
    "stats.yellow_cards" as yellow_cards,
    "stats.red_cards" as red_cards,
    "stats.saves" as saves,
    "stats.bonus" as bonus,
    "stats.bps" as bps,
    cast("stats.influence" as float) as influence,
    cast("stats.creativity" as float) as creativity,
    cast("stats.threat" as float) as threat,
    cast("stats.ict_index" as float) as ict_index,
    "stats.clearances_blocks_interceptions" as clearances_blocks_interceptions,
    "stats.recoveries" as recoveries,
    "stats.tackles" as tackles,
    "stats.defensive_contribution" as defensive_contribution,
    "stats.starts" as starts,
    cast("stats.expected_goals" as float) as xG,
    cast("stats.expected_assists" as float) as xA,
    cast("stats.expected_goal_involvements" as float) as expected_goal_involvements,
    cast("stats.expected_goals_conceded" as float) as expected_goals_conceded,
    "stats.in_dreamteam" as in_dreamteam,
    "stats.total_points" as total_points,
    ingested_at
from {{ source('raw_layer', 'raw_gw_data') }}
qualify row_number() over (partition by id, gameweek order by ingested_at desc) = 1
